In [1]:
import numpy as np
import cv2
import matplotlib.pyplot as plt

In [2]:
#P1.i

A = np.array([[66, -10, 16, 14, 65], [-91, 28, 97, -42 ,4],[13, 50, -96, 92, -85],
              [21, -96, 49, 34, 93],[-53, 96, 80, 96, -68]])
print(A)
B = np.array([[1, 1, 0, 1, 0], [1, 0, 1, 1, 1,], [0, 0, 0, 1, 0,], [1, 1, 0, 0, 1,], 
              [0, 0, 1, 1, 0]])
print(B)

[[ 66 -10  16  14  65]
 [-91  28  97 -42   4]
 [ 13  50 -96  92 -85]
 [ 21 -96  49  34  93]
 [-53  96  80  96 -68]]
[[1 1 0 1 0]
 [1 0 1 1 1]
 [0 0 0 1 0]
 [1 1 0 0 1]
 [0 0 1 1 0]]


In [3]:
#P1.ii

x = np.where(A < -70)
print(x)

(array([1, 2, 2, 3]), array([0, 2, 4, 1]))


In [4]:
#P1.iii

C = np.multiply(A,B)
print(C)

[[ 66 -10   0  14   0]
 [-91   0  97 -42   4]
 [  0   0   0  92   0]
 [ 21 -96   0   0  93]
 [  0   0  80  96   0]]


In [5]:
#P1.iv

ip3c5r = np.inner(C[4,:],C[:,2])
print(C[4,:])
print(C[:,2])

[ 0  0 80 96  0]
[ 0 97  0  0 80]


In [6]:
#P1.v

fcmax = np.amax(C[:,3])
print(fcmax)
ifcmax = np.where(C == 96)
print(ifcmax)

96
(array([4]), array([3]))


In [7]:
#P1.vi

D = np.array([C[0,:]*C[0,:], C[0,:]*C[1,:], C[0,:]*C[2,:], C[0,:]*C[3,:], C[0,:]*C[4,:]])
print(D)

[[ 4356   100     0   196     0]
 [-6006     0     0  -588     0]
 [    0     0     0  1288     0]
 [ 1386   960     0     0     0]
 [    0     0     0  1344     0]]


In [8]:
#P1.vii

E = np.array([D[0,:]*D[0,:], D[0,:]*D[1,:], D[0,:]*D[2,:], D[0,:]*D[3,:], D[0,:]*D[4,:]])
print(E)

[[ 18974736     10000         0     38416         0]
 [-26162136         0         0   -115248         0]
 [        0         0         0    252448         0]
 [  6037416     96000         0         0         0]
 [        0         0         0    263424         0]]


In [ ]:

    # START
    if haveIBeenHereBefore(loc, nextStep) is True:
        nextStep = loc[-1] + np.array([0, -1])
    if detectObject(loc, obj, 'S'):
        nextStep = loc[-1] + np.array([0, -1])
        if detectObject(loc, obj, 'W' ):
            nextStep = loc[-1] + np.array([0, 1])
            if detectObject(loc, obj,'E'):
                nextStep = loc[-1] + np.array([-1, 0])       
    # STOP


In [9]:
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt
import random
from skimage import draw
import cv2

def generate_one_shape(numSides, orientation):
    xCenter = random.randint(200,300)
    yCenter = random.randint(200,300)
    theta = np.linspace(0, 2*np.pi, numSides + 1)
    theta = theta - np.pi/orientation;
    radius = random.randint(40,150)
    x = radius * np.cos(theta) + xCenter;
    y = radius * np.sin(theta) + yCenter;
    binaryImage = poly2mask(x, y, (500, 500))
    return binaryImage

def poly2mask(vertex_row_coords, vertex_col_coords, shape):
    fill_row_coords, fill_col_coords = draw.polygon(vertex_row_coords, vertex_col_coords, shape)
    mask = np.zeros(shape, dtype=np.bool)
    mask[fill_row_coords, fill_col_coords] = True
    return mask

def generator1():
    empty = np.zeros((500,500))
    label = random.randint(0, 1)
    shape = random.randint(3, 4)
    orientation = random.randint(1, 6)
    test_img = generate_one_shape(shape, orientation)
    if label == 0:
        orientation = random.randint(1, 6)
        A = generate_one_shape(shape, orientation)
        B = empty
    else:
        A = empty
        orientation = random.randint(1, 6)
        B = generate_one_shape(shape, orientation)
    return A,B, test_img, label

def generator2():
    label = random.randint(0, 1)
    shape = random.randint(3, 4)
    orientation = random.randint(1, 10)
    test_img = generate_one_shape(shape, orientation)
    orientation = random.randint(1, 10)
    if label == 0:
        A = test_img
        B = generate_one_shape(7-shape, orientation)
    else:
        A = generate_one_shape(7-shape, orientation)
        B = test_img
    return A,B, test_img, label

def generator3():
    label = random.randint(0, 1)
    orientation = random.randint(1, 10)
    test_img = generate_one_shape(3, orientation)
    orientation = random.randint(1, 10)
    if label == 0:
        A = generate_one_shape(3, orientation)
        B = generate_one_shape(4, orientation)
    else:
        A = generate_one_shape(4, orientation)
        B = generate_one_shape(3, orientation)
    return A,B, test_img, label

def generator4():
    label = random.randint(0, 1)
    shape = random.randint(3, 6)
    if label == 0:
        orientation = random.randint(1, 10)
        test_img = generate_one_shape(shape, orientation)
        orientation = random.randint(1, 10)
        A = generate_one_shape(shape, orientation)
        orientation = random.randint(1, 10)
        B = generate_one_shape(9-shape, orientation)
    else:
        orientation = random.randint(1, 10)
        test_img = generate_one_shape(shape, orientation)
        orientation = random.randint(1, 10)
        A = generate_one_shape(9-shape, orientation)
        orientation = random.randint(1, 10)
        B = generate_one_shape(shape, orientation)
    return A,B, test_img, label

def classifier1(A, B, test_img):
    nothing = np.zeros((500,500))
    if np.all(A == nothing):    
        return 1
    elif np.all(B == nothing):
        return 0
    else:
        return 0

def classifier2(A, B, test_img):
    if np.all(A == test_img):    
        return 0
    elif np.all(B == test_img):
        return 1
    else:
        return 0

def classifier3(A, B, test_img):
    pil_img0 = Image.fromarray(A) 
    img0 = np.uint8(pil_img0)          
    contours0,h = cv2.findContours(img0,1,2)
    for cnt0 in contours0:
        approx0 = cv2.approxPolyDP(cnt0,0.01*cv2.arcLength(cnt0,True),True)

    pil_imgt = Image.fromarray(test_img)     
    imgt = np.uint8(pil_imgt)          
    contours,h = cv2.findContours(imgt,1,2)
    for cnt in contours:
        approx = cv2.approxPolyDP(cnt,0.01*cv2.arcLength(cnt,True),True)
    if len(approx) == len(approx0):
        return 0
    elif len(approx) != len(approx0):
        return 1

def classifier4(A, B, test_img):
    pil_img0 = Image.fromarray(A)     
    img0 = np.uint8(pil_img0)          
    contours0,h = cv2.findContours(img0,1,2)
    for cnt0 in contours0:
        approx0 = cv2.approxPolyDP(cnt0,0.01*cv2.arcLength(cnt0,True),True)

    pil_imgt = Image.fromarray(test_img)    
    imgt = np.uint8(pil_imgt)          
    contours,h = cv2.findContours(imgt,1,2)
    for cnt in contours:
        approx = cv2.approxPolyDP(cnt,0.01*cv2.arcLength(cnt,True),True)
    if len(approx) == len(approx0):
        return 0
    elif len(approx) != len(approx0):
        return 1
    return 0

for i in range(4):
    correct_count = 0
    for j in range(100):
        if i == 0:
            block0,block1,test_img,label = generator1()
            output = classifier1(block0,block1,test_img)
        elif i == 1:
            block0,block1,test_img,label = generator2()
            output = classifier2(block0,block1,test_img)
        elif i == 2:
            block0,block1,test_img,label = generator3()
            output = classifier3(block0,block1,test_img)
        else: 
            block0,block1,test_img,label = generator4()
            output = classifier4(block0,block1,test_img)
        if output == label:
            correct_count += 1
    accuracy = correct_count / 100
    print('The accuracy of question %d is %f\n'%(i+1,accuracy))

The accuracy of question 1 is 1.000000

The accuracy of question 2 is 1.000000

The accuracy of question 3 is 1.000000

The accuracy of question 4 is 1.000000

